version: "3.8"

services:
  wall_display2:
    build: .
    image: wall-display2:v0.1.099
    container_name: wall_display2
    ports:
      - "9099:9099"
    environment:
      NODE_ENV: production
    restart: unless-stopped
    labels:
      - "traefik.http.routers.wall_display2_int.rule=Host(`walldisplay2.sinabian.se`) && HeadersRegexp(`X-Real-Ip`, `(^127\\.)|(^10\\.)|(^172\\.1[6-9]\\.)|(^172\\.2[0-9]\\.)|(^172\\.3[0-1]\\.)|(^192\\.168\\.)`)"
      - "traefik.http.routers.wall_display2_int.priority=100"
      - "traefik.http.routers.wall_display2_int.tls=true"
      - "traefik.http.routers.wall_display2_int.tls.certresolver=myresolver"
      - "traefik.http.routers.wall_display2_int.middlewares=nobasicauth"

      - "traefik.http.routers.wall_display2_ext.rule=Host(`walldisplay2.sinabian.se`)"
      - "traefik.http.routers.wall_display2_ext.priority=99"
      - "traefik.http.routers.wall_display2_ext.tls=true"
      - "traefik.http.routers.wall_display2_ext.tls.certresolver=myresolver"
      - "traefik.http.routers.wall_display2_ext.middlewares=basicauth"

      - "traefik.http.services.wall_display2.loadbalancer.server.port=9099"
      - "traefik.http.services.wall_display2.loadbalancer.server.scheme=http"
